### ISSUE TITLE
Review in progress

### ISSUE THREAD

**Issue by zahraoui-mohammed** [ou-sama1/Software-engineer-challenge#1]
Hello Mr @ou-sama1,

After reviewing your latest updates, here are some points that require your attention. It is essential to carefully address these items, as they directly impact the overall quality and functionality of the application:

- Return types and type hints are missing.
- Follow PSR 1-2 notations.
- The user can upload the product Image when creating the product through the command (from an url)
- Use dependency injection when it's missing

Please ensure that all the above issues are rectified. It is important to carefully follow the instructions and review the "Links and Resources" section to avoid missing any key components. Your attention to these details is critical to ensure the strength of your coding quality.

**Comment by ou-sama1** [comment]
Hello @zahraoui-mohammed ,

Thank you for the feedback, I will do my best to fix the issues.
I have a question regarding the second and third listed issues, could you give me an example of where I didnt follow the PSR 1-2 notations? and whats missing in my definition of the product?

Thank you again.

**Comment by ou-sama1** [comment]
Hello Mr @zahraoui-mohammed 

I have made new changes
